exclude: "^docs/|/migrations/"
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: ["--config=mypy-precommit.ini", "--show-error-codes", "--no-error-summary"]
        additional_dependencies:
          - django-stubs
          - djangorestframework-stubs
          - celery==5.4.0
          - django-environ==0.11.2
          - django==5.1.2
          - djangorestframework==3.14.0
        verbose: true
        stages: [manual]  # 자동으로 실행되지 않고 수동으로만 실행


# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
