# Generated by Django 4.1.8 on 2023-04-12 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("alias", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CHECKING_ACCOUNT", "입출금"),
                            ("SAVINGS_ACCOUNT", "저금"),
                            ("INSTALLMENT_SAVING", "적금"),
                            ("TIME_DEPOSIT", "예금"),
                            ("CREDIT_CARD", "신용카드"),
                        ],
                        default="CHECKING_ACCOUNT",
                        max_length=30,
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("datetime", models.DateTimeField()),
                ("note", models.TextField(blank=True, null=True)),
                ("is_internal", models.BooleanField(default=False)),
                ("requires_detail", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SERVICE", "서비스"),
                            ("DAILY_NECESSITY", "생필품"),
                            ("MEMBERSHIP", "맴버쉽"),
                            ("GROCERY", "식료품"),
                            ("EAT_OUT", "외식"),
                            ("CLOTHING", "옷"),
                            ("PRESENT", "선물"),
                            ("CAR", "차/주유"),
                            ("HOUSING", "집/월세"),
                            ("LEISURE", "여가"),
                            ("MEDICAL", "의료비"),
                            ("PARENTING", "육아"),
                            ("TRANSFER", "이체"),
                            ("ETC", "ETC"),
                        ],
                        default="ETC",
                        max_length=30,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="money.account"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UseFor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(max_length=40)),
                ("amount", models.FloatField()),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="use_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="money.usefor",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="money.bank"
            ),
        ),
    ]
