# Generated by Django 4.1.8 on 2023-04-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="balance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
