# Generated by Django 4.1.8 on 2023-04-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0002_transaction_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="amount",
            field=models.FloatField(default=0),
        ),
    ]
