# Generated by Django 4.1.8 on 2023-04-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0003_alter_account_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="last_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
