# Generated by Django 4.1.8 on 2023-04-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0004_account_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="last_transaction",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("SERVICE", "서비스"),
                    ("DAILY_NECESSITY", "생필품"),
                    ("MEMBERSHIP", "맴버쉽"),
                    ("GROCERY", "식료품"),
                    ("EAT_OUT", "외식"),
                    ("CLOTHING", "옷"),
                    ("PRESENT", "선물"),
                    ("CAR", "차/주유"),
                    ("HOUSING", "집/월세"),
                    ("LEISURE", "여가"),
                    ("MEDICAL", "의료비"),
                    ("PARENTING", "육아"),
                    ("TRANSFER", "이체"),
                    ("INTEREST", "이자"),
                    ("ETC", "ETC"),
                ],
                default="ETC",
                max_length=30,
            ),
        ),
    ]
