# Generated by Django 4.1.8 on 2023-04-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0008_rename_use_for_transaction_retailer"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="type",
            field=models.CharField(
                choices=[
                    ("ETC", "Etc"),
                    ("MARKET", "Market"),
                    ("PERSON", "Person"),
                    ("BANK", "Bank"),
                    ("SERVICE", "Service"),
                ],
                default="ETC",
                max_length=20,
            ),
        ),
    ]
