# Generated by Django 4.1.8 on 2023-04-21 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0010_retailer_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="related_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="money.transaction",
            ),
        ),
    ]
