# Generated by Django 4.1.8 on 2023-04-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0011_transaction_related_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[("WON", "원화"), ("USD", "달러")], default="USD", max_length=3
            ),
        ),
    ]
