# Generated by Django 4.1.8 on 2023-04-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0012_account_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], default="USD", max_length=3
            ),
        ),
    ]
