# Generated by Django 4.1.8 on 2023-04-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0013_alter_account_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="transactiondetail",
            name="count",
            field=models.IntegerField(default=1),
        ),
    ]
