# Generated by Django 4.1.8 on 2023-04-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0015_alter_transactiondetail_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactiondetail",
            name="item",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="money.detailitem",
            ),
            preserve_default=False,
        ),
    ]
