# Generated by Django 4.1.8 on 2023-04-29 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0016_transactiondetail_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("gross_pay", models.FloatField()),
                ("total_adjustment", models.FloatField()),
                ("total_withheld", models.FloatField()),
                ("net_pay", models.FloatField()),
                ("pay_detail", models.JSONField()),
                ("adjustment_detail", models.JSONField()),
                ("tax_detail", models.JSONField()),
                ("deduction_detail", models.JSONField()),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money.transaction",
                    ),
                ),
            ],
        ),
    ]
