# Generated by Django 4.1.8 on 2023-04-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0017_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="total_deduction",
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
