# Generated by Django 4.1.8 on 2023-04-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0018_salary_total_deduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("CHECKING_ACCOUNT", "입출금"),
                    ("SAVINGS_ACCOUNT", "저금"),
                    ("INSTALLMENT_SAVING", "적금"),
                    ("TIME_DEPOSIT", "예금"),
                    ("CREDIT_CARD", "신용카드"),
                    ("STOCK", "주식"),
                ],
                default="CHECKING_ACCOUNT",
                max_length=30,
            ),
        ),
    ]
