# Generated by Django 4.1.8 on 2023-05-02 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0019_alter_account_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="retailer",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="transaction",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="last_transaction",
            field=models.DateField(blank=True, null=True),
        ),
    ]
