# Generated by Django 4.1.8 on 2023-05-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0025_alter_detailitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="detailitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("ETC", "ETC"),
                    ("FRUIT", "과일"),
                    ("ALCOHOL", "주류"),
                    ("DRINK", "음료"),
                    ("SAUCE", "소스"),
                    ("MEAT", "육류"),
                    ("VEGETABLE", "채소"),
                    ("DAIRY", "유제품"),
                    ("WRAP", "포장지"),
                    ("SNACK", "스낵"),
                    ("NOODLE", "면"),
                    ("BREAD", "빵"),
                    ("DRUG", "약"),
                    ("TAX", "TAX"),
                    ("SEAFOOD", "해산물"),
                    ("INGREDIENT", "식재료"),
                    ("APPLIANCE", "가전"),
                    ("STATIONERY", "문구류"),
                    ("BATH", "욕실용품"),
                    ("BABY", "육아용품"),
                    ("COOKER", "주방용품"),
                    ("FOOD", "식품"),
                    ("CLOTHING", "의류"),
                    ("UNK", "Unknown"),
                ],
                default="ETC",
                max_length=10,
            ),
        ),
    ]
