# Generated by Django 4.1.8 on 2023-05-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0026_account_is_active_alter_detailitem_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmazonOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("item", models.TextField()),
            ],
        ),
    ]
