# Generated by Django 4.1.8 on 2023-05-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0027_amazonorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="amazonorder",
            name="is_returned",
            field=models.BooleanField(default=False),
        ),
    ]
