# Generated by Django 4.1.8 on 2023-05-04 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0028_amazonorder_is_returned"),
    ]

    operations = [
        migrations.AddField(
            model_name="amazonorder",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="money.transaction",
            ),
        ),
    ]
