# Generated by Django 4.1.8 on 2023-05-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0029_amazonorder_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactiondetail",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="money.transaction",
            ),
        ),
    ]
