# Generated by Django 4.1.8 on 2023-05-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0032_exchange"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="balance",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="category",
            field=models.CharField(
                choices=[
                    ("SERVICE", "서비스"),
                    ("DAILY_NECESSITY", "생필품"),
                    ("MEMBERSHIP", "맴버쉽"),
                    ("GROCERY", "식료품"),
                    ("EAT_OUT", "외식"),
                    ("CLOTHING", "옷"),
                    ("PRESENT", "선물"),
                    ("CAR", "차/주유"),
                    ("HOUSING", "집/월세"),
                    ("LEISURE", "여가"),
                    ("MEDICAL", "의료비"),
                    ("PARENTING", "육아"),
                    ("TRANSFER", "이체"),
                    ("INTEREST", "이자"),
                    ("INCOME", "소득"),
                    ("ETC", "ETC"),
                    ("STOCK", "주식"),
                ],
                default="ETC",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("SERVICE", "서비스"),
                    ("DAILY_NECESSITY", "생필품"),
                    ("MEMBERSHIP", "맴버쉽"),
                    ("GROCERY", "식료품"),
                    ("EAT_OUT", "외식"),
                    ("CLOTHING", "옷"),
                    ("PRESENT", "선물"),
                    ("CAR", "차/주유"),
                    ("HOUSING", "집/월세"),
                    ("LEISURE", "여가"),
                    ("MEDICAL", "의료비"),
                    ("PARENTING", "육아"),
                    ("TRANSFER", "이체"),
                    ("INTEREST", "이자"),
                    ("INCOME", "소득"),
                    ("ETC", "ETC"),
                    ("STOCK", "주식"),
                ],
                default="ETC",
                max_length=30,
            ),
        ),
    ]
