# Generated by Django 4.1.8 on 2023-05-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0033_stocktransaction_balance_alter_retailer_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="balance",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
