# Generated by Django 4.1.8 on 2023-05-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0035_alter_account_type_alter_retailer_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="first_transaction",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="type",
            field=models.CharField(
                choices=[
                    ("ETC", "Etc"),
                    ("STORE", "Store"),
                    ("PERSON", "Person"),
                    ("BANK", "Bank"),
                    ("SERVICE", "Service"),
                    ("INCOME", "Income"),
                ],
                default="ETC",
                max_length=20,
            ),
        ),
    ]
