# Generated by Django 4.1.8 on 2023-05-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0036_account_first_transaction_alter_retailer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="first_added",
            field=models.BooleanField(default=False),
        ),
    ]
