# Generated by Django 4.1.8 on 2023-05-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0037_account_first_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchange",
            name="ratio_per_krw",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
