# Generated by Django 4.1.8 on 2023-05-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0038_exchange_ratio_per_krw"),
    ]

    operations = [
        migrations.AddField(
            model_name="amazonorder",
            name="return_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="returned_order",
                to="money.transaction",
            ),
        ),
    ]
