# Generated by Django 4.1.8 on 2023-05-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0039_amazonorder_return_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detailitem",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="detailitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("ETC", "ETC"),
                    ("FRUIT", "과일"),
                    ("ALCOHOL", "주류"),
                    ("DRINK", "음료"),
                    ("SAUCE", "소스"),
                    ("MEAT", "육류"),
                    ("VEGETABLE", "채소"),
                    ("DAIRY", "유제품"),
                    ("WRAP", "포장지"),
                    ("SNACK", "스낵"),
                    ("NOODLE", "면"),
                    ("BREAD", "빵"),
                    ("DRUG", "약"),
                    ("TAX", "TAX"),
                    ("SEAFOOD", "해산물"),
                    ("INGREDIENT", "식재료"),
                    ("APPLIANCE", "가전"),
                    ("STATIONERY", "문구류"),
                    ("BATH", "욕실용품"),
                    ("BABY", "육아용품"),
                    ("COOKER", "주방용품"),
                    ("FOOD", "식품"),
                    ("CLOTHING", "의류"),
                    ("FUNITURE", "가구"),
                    ("SPORTING", "운동용품"),
                    ("UNK", "Unknown"),
                ],
                default="ETC",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="type",
            field=models.CharField(
                choices=[
                    ("ETC", "Etc"),
                    ("STORE", "Store"),
                    ("PERSON", "Person"),
                    ("BANK", "Bank"),
                    ("SERVICE", "Service"),
                    ("INCOME", "Income"),
                    ("RESTAURANT", "Restaurant"),
                ],
                default="ETC",
                max_length=20,
            ),
        ),
    ]
