# Generated by Django 4.1.8 on 2023-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0040_alter_detailitem_options_alter_detailitem_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmountSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "currency",
                    models.CharField(
                        choices=[("KRW", "원화"), ("USD", "달러")], max_length=3
                    ),
                ),
                ("amount", models.FloatField()),
                ("summary", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
