# Generated by Django 4.1.8 on 2023-07-30 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0041_amountsnapshot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amazonorder",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="bank",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="stock",
            name="currency",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], default="USD", max_length=3
            ),
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("price", models.FloatField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="money.stock"
                    ),
                ),
            ],
        ),
    ]
