# Generated by Django 4.1.8 on 2023-08-12 21:49

from django.db import migrations
import django_choices_field.fields
import money.choices


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0042_alter_amazonorder_options_alter_bank_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("CHECKING_ACCOUNT", "입출금"),
                    ("SAVINGS_ACCOUNT", "저금"),
                    ("INSTALLMENT_SAVING", "적금"),
                    ("TIME_DEPOSIT", "예금"),
                    ("CREDIT_CARD", "신용카드"),
                    ("STOCK", "주식"),
                    ("LOAN", "대출"),
                ],
                choices_enum=money.choices.AccountType,
                default="CHECKING_ACCOUNT",
                max_length=18,
            ),
        ),
    ]
