# Generated by Django 4.1.8 on 2023-08-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0044_alter_account_currency_alter_amountsnapshot_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(db_collation="C", max_length=200),
        ),
    ]
