# Generated by Django 4.1.8 on 2024-01-02 10:38

from django.db import migrations
import django_choices_field.fields
import money.choices


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0045_alter_account_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchange",
            name="exchange_type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("ETC", "ETC"),
                    ("BANK", "은행"),
                    ("WIREBARLEY", "와이어바알리"),
                    ("CREDITCARD", "신용카드"),
                ],
                choices_enum=money.choices.ExchangeType,
                default="ETC",
                max_length=10,
            ),
        ),
    ]
