# Generated by Django 4.1.8 on 2024-01-24 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0046_exchange_exchange_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="related_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="money.transaction",
            ),
        ),
    ]
