# Generated by Django 4.1.8 on 2024-04-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0048_account_amount_int_transaction_amount_int"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="amount_int",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount_int",
            field=models.BigIntegerField(default=0),
        ),
    ]
