# Generated by Django 4.1.8 on 2024-08-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0049_alter_account_amount_int_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="transaction_files/")),
                ("date", models.DateField()),
                ("note", models.TextField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="money.account",
                    ),
                ),
            ],
        ),
    ]
