# Generated by Django 4.2.15 on 2024-09-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0050_transactionfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="W2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("wages", models.DecimalField(decimal_places=2, max_digits=10)),
                ("income_tax", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "social_security_wages",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "social_security_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "medicare_wages",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("medicare_tax", models.DecimalField(decimal_places=2, max_digits=10)),
                ("box_12", models.JSONField(blank=True, null=True)),
                ("box_14", models.CharField(blank=True, null=True)),
            ],
        ),
    ]
