# Generated by Django 4.2.15 on 2024-09-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0051_w2"),
    ]

    operations = [
        migrations.AddField(
            model_name="w2",
            name="year",
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
