# Generated by Django 5.1.2 on 2025-03-02 22:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0053_amazonorder_created_at_amazonorder_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0"),
                max_digits=15,
                null=True,
            ),
        ),
    ]
