# Generated by Django 5.1.2 on 2025-03-02 23:05

import django_choices_field.fields
import money.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0054_alter_stocktransaction_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="amountsnapshot",
            name="amount_int",
            field=models.BigIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="amountsnapshot",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="amountsnapshot",
            name="currency",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("KRW", "원화"), ("USD", "달러")],
                choices_enum=money.choices.CurrencyType,
                default="USD",
                max_length=3,
            ),
        ),
    ]
