# Generated by Django 5.1.2 on 2025-03-03 02:08

import django_choices_field.fields
import money.choices
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0055_amountsnapshot_amount_int_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="currency",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("KRW", "원화"), ("USD", "달러")],
                choices_enum=money.choices.CurrencyType,
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="w2",
            name="currency",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("KRW", "원화"), ("USD", "달러")],
                choices_enum=money.choices.CurrencyType,
                default="USD",
                max_length=3,
            ),
        ),
    ]
