# Generated by Django 5.1.2 on 2025-03-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0056_salary_currency_w2_currency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bank",
            options={},
        ),
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], default="USD", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("CHECKING_ACCOUNT", "입출금"),
                    ("SAVINGS_ACCOUNT", "저금"),
                    ("INSTALLMENT_SAVING", "적금"),
                    ("TIME_DEPOSIT", "예금"),
                    ("CREDIT_CARD", "신용카드"),
                    ("STOCK", "주식"),
                    ("LOAN", "대출"),
                ],
                default="CHECKING_ACCOUNT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="amountsnapshot",
            name="currency",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], default="USD", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="detailitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("ETC", "ETC"),
                    ("FRUIT", "과일"),
                    ("ALCOHOL", "주류"),
                    ("DRINK", "음료"),
                    ("SAUCE", "소스"),
                    ("MEAT", "육류"),
                    ("VEGETABLE", "채소"),
                    ("DAIRY", "유제품"),
                    ("WRAP", "포장지"),
                    ("SNACK", "스낵"),
                    ("NOODLE", "면"),
                    ("BREAD", "빵"),
                    ("DRUG", "약"),
                    ("TAX", "TAX"),
                    ("SEAFOOD", "해산물"),
                    ("INGREDIENT", "식재료"),
                    ("APPLIANCE", "가전"),
                    ("STATIONERY", "문구류"),
                    ("BATH", "욕실용품"),
                    ("BABY", "육아용품"),
                    ("COOKER", "주방용품"),
                    ("FOOD", "식품"),
                    ("CLOTHING", "의류"),
                    ("FUNITURE", "가구"),
                    ("SPORTING", "운동용품"),
                    ("UNK", "Unknown"),
                ],
                default="ETC",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="exchange_type",
            field=models.CharField(
                choices=[
                    ("ETC", "ETC"),
                    ("BANK", "은행"),
                    ("WIREBARLEY", "와이어바알리"),
                    ("CREDITCARD", "신용카드"),
                ],
                default="ETC",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="from_currency",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="to_currency",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="category",
            field=models.CharField(
                choices=[
                    ("SERVICE", "서비스"),
                    ("DAILY_NECESSITY", "생필품"),
                    ("MEMBERSHIP", "맴버쉽"),
                    ("GROCERY", "식료품"),
                    ("EAT_OUT", "외식"),
                    ("CLOTHING", "옷"),
                    ("PRESENT", "선물"),
                    ("CAR", "차/주유/운임"),
                    ("HOUSING", "집/월세"),
                    ("LEISURE", "여가"),
                    ("MEDICAL", "의료비"),
                    ("PARENTING", "육아"),
                    ("TRANSFER", "이체"),
                    ("INTEREST", "이자"),
                    ("INCOME", "소득"),
                    ("ETC", "ETC"),
                    ("STOCK", "주식"),
                    ("CASH", "현금"),
                ],
                default="ETC",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="type",
            field=models.CharField(
                choices=[
                    ("ETC", "Etc"),
                    ("STORE", "Store"),
                    ("PERSON", "Person"),
                    ("BANK", "Bank"),
                    ("SERVICE", "Service"),
                    ("INCOME", "Income"),
                    ("RESTAURANT", "Restaurant"),
                ],
                default="ETC",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="currency",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], default="USD", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="currency",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], default="USD", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("SERVICE", "서비스"),
                    ("DAILY_NECESSITY", "생필품"),
                    ("MEMBERSHIP", "맴버쉽"),
                    ("GROCERY", "식료품"),
                    ("EAT_OUT", "외식"),
                    ("CLOTHING", "옷"),
                    ("PRESENT", "선물"),
                    ("CAR", "차/주유/운임"),
                    ("HOUSING", "집/월세"),
                    ("LEISURE", "여가"),
                    ("MEDICAL", "의료비"),
                    ("PARENTING", "육아"),
                    ("TRANSFER", "이체"),
                    ("INTEREST", "이자"),
                    ("INCOME", "소득"),
                    ("ETC", "ETC"),
                    ("STOCK", "주식"),
                    ("CASH", "현금"),
                ],
                default="ETC",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="w2",
            name="currency",
            field=models.CharField(
                choices=[("KRW", "원화"), ("USD", "달러")], default="USD", max_length=3
            ),
        ),
    ]
