# Generated by Django 5.1.2 on 2025-03-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0057_alter_bank_options_alter_account_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("ETC", "기타"),
                    ("FRUIT", "과일"),
                    ("ALCOHOL", "주류"),
                    ("DRINK", "음료"),
                    ("SAUCE", "소스"),
                    ("MEAT", "육류"),
                    ("VEGETABLE", "채소"),
                    ("DAIRY", "유제품"),
                    ("WRAP", "포장지"),
                    ("SNACK", "스낵"),
                    ("NOODLE", "면"),
                    ("BREAD", "빵"),
                    ("DRUG", "약"),
                    ("TAX", "세금"),
                    ("SEAFOOD", "해산물"),
                    ("INGREDIENT", "식재료"),
                    ("APPLIANCE", "가전"),
                    ("STATIONERY", "문구류"),
                    ("BATH", "욕실용품"),
                    ("BABY", "육아용품"),
                    ("COOKER", "주방용품"),
                    ("FOOD", "식품"),
                    ("CLOTHING", "의류"),
                    ("FURNITURE", "가구"),
                    ("SPORTING", "운동용품"),
                    ("UNKNOWN", "알 수 없음"),
                ],
                default="ETC",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="exchange_type",
            field=models.CharField(
                choices=[
                    ("ETC", "기타"),
                    ("BANK", "은행"),
                    ("WIREBARLEY", "와이어바알리"),
                    ("CREDITCARD", "신용카드"),
                ],
                default="ETC",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="category",
            field=models.CharField(
                choices=[
                    ("SERVICE", "서비스"),
                    ("DAILY_NECESSITY", "생필품"),
                    ("MEMBERSHIP", "맴버쉽"),
                    ("GROCERY", "식료품"),
                    ("EAT_OUT", "외식"),
                    ("CLOTHING", "옷"),
                    ("PRESENT", "선물"),
                    ("CAR", "차/주유/운임"),
                    ("HOUSING", "집/월세"),
                    ("LEISURE", "여가"),
                    ("MEDICAL", "의료비"),
                    ("PARENTING", "육아"),
                    ("TRANSFER", "이체"),
                    ("INTEREST", "이자"),
                    ("INCOME", "소득"),
                    ("STOCK", "주식"),
                    ("CASH", "현금"),
                    ("ETC", "기타"),
                ],
                default="ETC",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="type",
            field=models.CharField(
                choices=[
                    ("ETC", "기타"),
                    ("STORE", "상점"),
                    ("PERSON", "개인"),
                    ("BANK", "은행"),
                    ("SERVICE", "서비스"),
                    ("INCOME", "수입"),
                    ("RESTAURANT", "식당"),
                ],
                default="ETC",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("SERVICE", "서비스"),
                    ("DAILY_NECESSITY", "생필품"),
                    ("MEMBERSHIP", "맴버쉽"),
                    ("GROCERY", "식료품"),
                    ("EAT_OUT", "외식"),
                    ("CLOTHING", "옷"),
                    ("PRESENT", "선물"),
                    ("CAR", "차/주유/운임"),
                    ("HOUSING", "집/월세"),
                    ("LEISURE", "여가"),
                    ("MEDICAL", "의료비"),
                    ("PARENTING", "육아"),
                    ("TRANSFER", "이체"),
                    ("INTEREST", "이자"),
                    ("INCOME", "소득"),
                    ("STOCK", "주식"),
                    ("CASH", "현금"),
                    ("ETC", "기타"),
                ],
                default="ETC",
                max_length=30,
            ),
        ),
    ]
