# Generated by Django 5.1.2 on 2025-03-09 07:29

import django_choices_field.fields
import money.choices
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0058_alter_detailitem_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bank",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("KRW", "원화"), ("USD", "달러")],
                choices_enum=money.choices.CurrencyType,
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("CHECKING_ACCOUNT", "입출금"),
                    ("SAVINGS_ACCOUNT", "저금"),
                    ("INSTALLMENT_SAVING", "적금"),
                    ("TIME_DEPOSIT", "예금"),
                    ("CREDIT_CARD", "신용카드"),
                    ("STOCK", "주식"),
                    ("LOAN", "대출"),
                ],
                choices_enum=money.choices.AccountType,
                default="CHECKING_ACCOUNT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="amountsnapshot",
            name="currency",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("KRW", "원화"), ("USD", "달러")],
                choices_enum=money.choices.CurrencyType,
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="detailitem",
            name="category",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("ETC", "기타"),
                    ("FRUIT", "과일"),
                    ("ALCOHOL", "주류"),
                    ("DRINK", "음료"),
                    ("SAUCE", "소스"),
                    ("MEAT", "육류"),
                    ("VEGETABLE", "채소"),
                    ("DAIRY", "유제품"),
                    ("WRAP", "포장지"),
                    ("SNACK", "스낵"),
                    ("NOODLE", "면"),
                    ("BREAD", "빵"),
                    ("DRUG", "약"),
                    ("TAX", "세금"),
                    ("SEAFOOD", "해산물"),
                    ("INGREDIENT", "식재료"),
                    ("APPLIANCE", "가전"),
                    ("STATIONERY", "문구류"),
                    ("BATH", "욕실용품"),
                    ("BABY", "육아용품"),
                    ("COOKER", "주방용품"),
                    ("FOOD", "식품"),
                    ("CLOTHING", "의류"),
                    ("FURNITURE", "가구"),
                    ("SPORTING", "운동용품"),
                    ("UNKNOWN", "알 수 없음"),
                ],
                choices_enum=money.choices.DetailItemCategory,
                default="ETC",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="exchange_type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("ETC", "기타"),
                    ("BANK", "은행"),
                    ("WIREBARLEY", "와이어바알리"),
                    ("CREDITCARD", "신용카드"),
                ],
                choices_enum=money.choices.ExchangeType,
                default="ETC",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="from_currency",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("KRW", "원화"), ("USD", "달러")],
                choices_enum=money.choices.CurrencyType,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="to_currency",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("KRW", "원화"), ("USD", "달러")],
                choices_enum=money.choices.CurrencyType,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="category",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("SERVICE", "서비스"),
                    ("DAILY_NECESSITY", "생필품"),
                    ("MEMBERSHIP", "맴버쉽"),
                    ("GROCERY", "식료품"),
                    ("EAT_OUT", "외식"),
                    ("CLOTHING", "옷"),
                    ("PRESENT", "선물"),
                    ("CAR", "차/주유/운임"),
                    ("HOUSING", "집/월세"),
                    ("LEISURE", "여가"),
                    ("MEDICAL", "의료비"),
                    ("PARENTING", "육아"),
                    ("TRANSFER", "이체"),
                    ("INTEREST", "이자"),
                    ("INCOME", "소득"),
                    ("STOCK", "주식"),
                    ("CASH", "현금"),
                    ("ETC", "기타"),
                ],
                choices_enum=money.choices.TransactionCategory,
                default="ETC",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("ETC", "기타"),
                    ("STORE", "상점"),
                    ("PERSON", "개인"),
                    ("BANK", "은행"),
                    ("SERVICE", "서비스"),
                    ("INCOME", "수입"),
                    ("RESTAURANT", "식당"),
                ],
                choices_enum=money.choices.RetailerType,
                default="ETC",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="currency",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("KRW", "원화"), ("USD", "달러")],
                choices_enum=money.choices.CurrencyType,
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="currency",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("KRW", "원화"), ("USD", "달러")],
                choices_enum=money.choices.CurrencyType,
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("SERVICE", "서비스"),
                    ("DAILY_NECESSITY", "생필품"),
                    ("MEMBERSHIP", "맴버쉽"),
                    ("GROCERY", "식료품"),
                    ("EAT_OUT", "외식"),
                    ("CLOTHING", "옷"),
                    ("PRESENT", "선물"),
                    ("CAR", "차/주유/운임"),
                    ("HOUSING", "집/월세"),
                    ("LEISURE", "여가"),
                    ("MEDICAL", "의료비"),
                    ("PARENTING", "육아"),
                    ("TRANSFER", "이체"),
                    ("INTEREST", "이자"),
                    ("INCOME", "소득"),
                    ("STOCK", "주식"),
                    ("CASH", "현금"),
                    ("ETC", "기타"),
                ],
                choices_enum=money.choices.TransactionCategory,
                default="ETC",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="w2",
            name="currency",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("KRW", "원화"), ("USD", "달러")],
                choices_enum=money.choices.CurrencyType,
                default="USD",
                max_length=3,
            ),
        ),
    ]
