# Generated by Django 5.1.2 on 2025-03-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0059_alter_bank_options_alter_account_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="amount_int",
        ),
        migrations.RemoveField(
            model_name="amountsnapshot",
            name="amount_int",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="amount_int",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="amount_int",
        ),
        migrations.RemoveField(
            model_name="transactiondetail",
            name="amount_int",
        ),
    ]
