# Generated by Django 5.1.2 on 2026-05-19 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0060_remove_account_amount_int_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annual_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "account",
                    models.OneToOneField(
                        limit_choices_to={"type": "CREDIT_CARD"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_card",
                        to="money.account",
                    ),
                ),
            ],
            options={
                "ordering": ["account__name"],
            },
        ),
        migrations.CreateModel(
            name="CreditCardBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CASHBACK", "캐시백"),
                            ("POINTS", "포인트"),
                            ("DISCOUNT", "할인"),
                            ("MILEAGE", "마일리지"),
                            ("OTHER", "기타"),
                        ],
                        default="DISCOUNT",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage (e.g. 5.00 = 5%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "cap_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Monthly cap in KRW",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "conditions",
                    models.TextField(
                        blank=True, default="", help_text="Conditions to qualify"
                    ),
                ),
                (
                    "credit_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="money.creditcard",
                    ),
                ),
            ],
            options={
                "ordering": ["-rate"],
            },
        ),
    ]
