# Generated by Django 4.1.8 on 2024-04-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
