# Generated by Django 5.1.2 on 2025-03-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_alter_person_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="birth_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="birth_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="birth_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
